#!/bin/sh
# Post-render fix for the assembled docs/ tree. Nothing else happens here:
#
#   sitemap.xml is generated by scripts/make-sitemap.sh from the rendered pages,
#   so there is no root sitemap.xml to copy and this script no longer does it.
#   It previously omitted cheatsheet.html, production.html and duckdb.html.
#
#   The PDF/ePub are NOT renamed. Quarto bakes the whole-book output filename
#   into the landing page's download link, so renaming after the render breaks
#   the link. An earlier version renamed "R,-Databases---SQL.pdf" to
#   "databases-and-sql.pdf", which left the advertised button 404ing.
#   The filename is set in _quarto.yml instead:
#     book:
#       output-file: databases-and-sql
#
# This script is retained as the hook for any future post-render fix, and is
# still called from .github/workflows/render.yml so that hook stays obvious.
exit 0